### PR TITLE
feature: system monitoring plugin

### PR DESCRIPTION
**Pull request by hiro-v**
- [x] add `systeminformation` deps
- [x] register extension points & cjs module exports
- [x] update app system information UI

### CODE REVIEW

**Comment by 0xSage** [comment]
@vuonghoainam what's the context on this PR? Can we deconflict and merge/close it yet?

**Comment by louis-jan** [comment]
Sorry @0xSage, this should be me, I will resolve this later tomorrow

**Comment by louis-jan** [comment]
Deconflict & updated checklist

**Comment by louis-jan** [comment]
Screenshot 2023-09-28 at 17 09 26

**Pull request merged**
