### PR TITLE
Anthropic Model Updates

### LINKED ISSUE #3889: idea: Add Claude 3.5 Sonnet 20241022
### Problem Statement

Latest claude 3.5 sonnet 20241022 model isn't integrated

### Feature Idea

- Add Claude 3.5 Sonnet [v20241022](https://www.anthropic.com/news/3-5-models-and-computer-use) model
- Increase `max-tokens` limit to `8192` for all sonnet models
- Append version to all claude model names

### PR: https://github.com/janhq/jan/pull/3888

### PR DESCRIPTION
**Pull request by px100**
### New Models Added:

- Claude 3 Opus 20240229/Latest
- Claude 3.5 Haiku 20241022/Latest
- Claude 3.5 Sonnet 20241022/Latest

### Enhanced Model Variants:
Claude 3.5 Sonnet models now support up to `8192` tokens for extended context processing.

### Version Updates:
Clearer naming conventions distinguishing between specific version releases (e.g., 20240620, 20241022) and their "latest" versions.

## Fixes Issues

- Closes #3889 

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Comment by afrizalhasbi** [comment]
Just commenting here, but is there any reason not to use the `-latest` tag? Would skip the hassle if a new version releases

**Comment by louis-jan** [comment]
Wow, thank you for the contribution, @px100. Could you bump the extension version to enable the migration?

**Comment by px100** [comment]
> Just commenting here, but is there any reason not to use the `-latest` tag? Would skip the hassle if a new version releases

Added `latest` version. Thanks

**Comment by px100** [comment]
> Wow, thank you for the contribution, @px100. Could you bump the extension version to enable the migration?

Bumped version of the existing models to `1.1`

**Comment by louis-jan** [comment]
Apologies, @px100, for the delayed update. Could you please help just keep `-latest model` and remove older versions? Help us rebase, we will proceed ASAP. 🙏

**Comment by louis-jan** [comment]
Hi @px100, FYI, I shortened the models list with the latest models

**Pull request merged**
