### PR TITLE
Fix scrolling issue on edit chat input

### LINKED ISSUE #2855: bug: Impossible to scroll when editing a chat input
**Describe the bug**
When editing a chat input, the scroll is disabled. The only way to go up and down through the input text is with the keys, which is not really user-friendly and kind of complicated. 

**Steps to reproduce**
1. Create a new thread.
2. Enter a pretty long message.
3. Edit this chat input.
4. Make sure the text is overflowing of the textarea.
4. See that you cannot scroll up or down. 

**Expected behavior**
I expect to be able to scroll up and down so I can edit my chat inputs easily.

**Screenshots**
image

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.12
- Processor: Intel Core i7
- RAM: 32GB

**Logs**
If the cause of the error is not clear, kindly provide your usage logs: https://jan.ai/docs/troubleshooting#how-to-get-error-logs

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

### PR DESCRIPTION
**Pull request by QuentinMacheda**
## Describe Your Changes

- Remove hidden overflow property to allow scrolling
- Update layout -> submit and cancel buttons are now below the textarea instead of being next to it.

## Fixes Issues

- Closes #2855

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Review by louis-jan — APPROVED** [review]
LGTM

**Comment by Van-QA** [comment]
hi @QuentinMacheda, could you help us resolve the linter issue, many thanks 
image

**Comment by QuentinMacheda** [comment]
> hi @QuentinMacheda, could you help us resolve the linter issue, many thanks image

Hi @Van-QA, sorry for that. I fixed the issue, do you want me to make another PR ?

**Comment by Van-QA** [comment]
thank @QuentinMacheda, that would be really helpful

**Pull request merged**
