### PR TITLE
fix: windows bug - control buttons close,max,min hidden

### PR DESCRIPTION
**Pull request by linhtran174**

### CODE REVIEW

**Comment by gn-hiro-v** [comment]
I tested on Mac, it's ok
[Mac screenshot](https://discord.com/channels/@me/1118744069733093458/1183974544722112512)

**Comment by urmauur** [comment]
Screenshot 2023-12-12 at 10 32 35

Tested on mac good on my side

**Review by urmauur — APPROVED** [review]

**Review by vuonghoainam — APPROVED** [review]

**Comment by linhtran174** [comment]
Why is the `close with comment` button red? Freaks me out. Should be purple for sth else

**Comment by linhtran174** [comment]
image
Good on Windows

**Pull request merged**
