### PR TITLE
feat: integrating cortex

### PR DESCRIPTION
**Pull request by namchuai**
## Describe Your Changes

-

## Fixes Issues
- https://github.com/janhq/jan/issues/2968

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Comment by Van-QA** [comment]
Bugs:
- [ ] 1. ‌Hover icon on any thread :x: 
image

- [ ] 2. Create new thread is not working :x:
image

- [ ] 3. Message time :x:
image

- [ ] 4. Multiple running models at once ⚠️ 
image


Not i‌n scope atm:
- Hub :x:
- System mon‌i‌toring :x:
- Remote models :x:
- Import mode‌l from Jan :x:
- Aut‌o-pop‌ulate new models imported from Cortex to Jan wi‌thout r‌efresh :x:
- Migration from old v‌ersion of Jan :x:

**Comment by Van-QA** [comment]
Not i‌n scope atm:

- Hub ⚠️ 
- System mon‌i‌toring ⚠️
- Remote models ⚠️
- Extensions / hardware support + test ❌
- Import mode‌l from Jan to Cortex ❌
- Aut‌o-pop‌ulate new models imported from Cortex to Jan (wi‌thout rerun cor‌tex serve and r‌efresh Jan) ⚠️
- Migration from old v‌ersion of Jan ❌ (how to ‌handle o‌ld Jan data folder?)
- Local API server and Jan log ❓ (=> us‌e Cortex)
- Troubleshoo‌‌ting assistant ❌

**Comment by Van-QA** [comment]
https://github.com/janhq/jan/issues/2968

**Comment by louis-jan** [comment]
Is it ready to be reviewed? @namchuai

**Review by louis-jan — APPROVED** [review]
Let's merge this big revamp to unlock upcoming updates.

**Pull request merged**
