### PR TITLE
fix: validate path in fs

### PR DESCRIPTION
**Pull request by marknguyen1302**
## Describe Your Changes

-  validate path in fs, only allow access to the file in the Jan folder

before the fix
   - invalid path:
image

after the fix:
   - valid path:
image
image
image

   - invalid path:
image
image
image

## Fixes Issues

- Closes #
- Closes #

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Comment by Van-QA** [comment]
https://github.com/janhq/jan/issues/2872

**Comment by louis-jan** [comment]
> related to #2872 Can you help me check the appendFil‌‌esyn‌c as w‌ell?

appendFileSync is a part of FS as well, see 23...44

**Comment by louis-jan** [comment]
Sneak a commit to fix the issue where symlink models are not visible. There still one vulnerability issue found, processing, don't merge yet.

**Review by louis-jan — APPROVED** [review]
LGHF

**Pull request merged**
