### PR TITLE
Chore: Add phi-3

### PR DESCRIPTION
**Pull request by hahuyhoang411**
## Describe Your Changes

- Add phi-3 to Jan

## Fixes Issues

- Closes #

## Self Checklist

- [x] Test Phi-3 locally
- [x] Add Phi-3
- [x] Bump package version

### CODE REVIEW

**Comment by hahuyhoang411** [comment]
works perfectly
image

**Review by louis-jan — APPROVED** [review]
LGTM

**Comment by Van-QA** [comment]
related to https://github.com/janhq/jan/issues/2800

**Comment by dmatora** [comment]
is there a nightly build or something, where it can already be used?

**Pull request merged**
