### PR TITLE
chore: update convo summary

### PR DESCRIPTION
**Pull request by louis-jan**
The conversation summary has been removed due to plugin-scoped inference refactoring. This reworked PR function operates on a new extension point & to avoid duplicated SSE fetch codes.

Screenshot 2023-10-17 at 21 33 44

### CODE REVIEW

**Comment by louis-jan** [comment]
User start with a very first prompt -> default summary is "User request: prompt" (similar to Chat GPT), attempt to summary the conversation, if the summary is too long, attempt in the next time until model get a good context

**Comment by 0xSage** [comment]
> User start with a very first prompt -> default summary is "User request: prompt" (similar to Chat GPT), attempt to summary the conversation, if the summary is too long, attempt in the next time until model get a good context.

Can we redact the "user request"? It can get a bit repetitive. Lets just do "prompt"

**Comment by louis-jan** [comment]
Yeah sure

**Review by namchuai — APPROVED** [review]
Thanks @louis-jan . LGTM

**Pull request merged**
