### PR TITLE
chore: update to yarn 4 and resolve dependency issues

### PR DESCRIPTION
**Pull request by Doko-Demo-Doa**
## Describe Your Changes

This PR update and specify package manager to yarn 4, stable version (4.3.1 as of today). Unless we want to bump into this [old issue](https://github.com/eslint/eslint/discussions/17215) and many other issues due to yarn 1 being obsolete.

Note: Yarn 4 is added as standalone mode to ensure it does not have problems with Docker or other package managers. `nodeLinker` is also set to `node-modules` for compatibility with old yarn version.

## Fixes Issues

N/A

## Self Checklist

- [x] Added relevant comments, esp in complex areas
- [x] Updated docs (for bug fixes / features)
- [x] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Comment by louis-jan** [comment]
Thank you @Doko-Demo-Doa

**Comment by Doko-Demo-Doa** [comment]
Conflicts resolved.

**Comment by louis-jan** [comment]
Sorry @Doko-Demo-Doa. As announced, we came to the decision to revert the latest integration. Please let us know if we can help cherry picking for a new PR or you can update from here.

**Comment by Doko-Demo-Doa** [comment]
@louis-jan Cherry-picking would be sufficient. Thank you.

**Comment by louis-jan** [comment]
> would

Thank you, we will proceed with a new PR.

**Comment by louis-jan** [comment]
Hi @Doko-Demo-Doa please help take a look at this PR https://github.com/janhq/jan/pull/3399. We shorten it a bit, since we don't want to commit unrelated changes.

**Comment by louis-jan** [comment]
@Doko-Demo-Doa I did a test and that update would break the build (e.g. nohoist) which is critical. We will deprioritize this.

**Comment by Doko-Demo-Doa** [comment]
@louis-jan understood. I will take a look asap. Please can you link to the failed pipeline?

**Pull request closed without merging**
