### PR TITLE
docs/update-api-reference

### PR DESCRIPTION
**Pull request by hieu-jan**
### PR Description: 
This PR makes a significant update to the entire API reference page including
- [x] Solved #630: OpenAI Compatible (Color: #0ca47c) and Jan (Color: #FEC928) -> Changed 
- [x] Solved #718: update /chat request object diffs 
- [x] Add introduction section
- [x] Update Title: API Reference | Jan
- [x] Update new changes based on new changes in specs
- [x] Change some configuration for API Reference to make it smooth

New Checklist:
- [x] Make API docs more concise, delete unnec copy
- [x] Show don’t tell, show the port in CURL sample instead
- [ ] Have CURL & payload examples for all endpoints
- [x] Remove openai compat tags at the properties level
- [x] update jan_url -> port in all CURL examples

### CODE REVIEW

**Review by 0xSage — CHANGES_REQUESTED** [review]
Can we try: 

1. Make the labels in line (instead of taking up space in a new line)
2. Can the labels be styled to look like a label instead of regular colored text?
3. Remove the Jan label altogether... I think it's implied when we don't have the `Openai compatible` label next to something
4. Remove the property-level labels when we've already labeled the endpoint, or it seems a bit repetitive. See below:
image

**Comment by 0xSage** [comment]
> Can we try:
> 
> 1. Make the labels in line (instead of taking up space in a new line)
> 2. Can the labels be styled to look like a label instead of regular colored text?
> 3. Remove the Jan label altogether... I think it's implied when we don't have the `Openai compatible` label next to something
> 4. Remove the property-level labels when we've already labeled the endpoint, or it seems a bit repetitive. See below:
>    image

Do you see the "webhook" label? Can we get this label to show up like that...

**Comment by hieu-jan** [comment]
Thanks for your feedback @0xSage. I will improve based on these feedback ASAP. 
Actually, I also want to make it like a Webhook label, but redoc lib only provides extensions for standard elements from OpenAPI 3.0. I also visited some similar projects using this library, seems they are only using standard from the template. Thus, my current solution for this PR is to implement and add style via HTML tag to display these label.

**Review by 0xSage — APPROVED** [review]
darn tootin'

**Pull request merged**
