### PR TITLE
Fix Bug for Chat Reply Goes off Screen

### PR DESCRIPTION
**Pull request by mishrababhishek**
## Describe Your Changes

- This PR Fixes the bug that chats sometime goes off screen 

## Fixes Issues

- bug: chat reply goes off screen (UI bug) #1377

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [x] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Comment by louis-jan** [comment]
Awesome, thank you @mishrababhishek

**Comment by mishrababhishek** [comment]
it is not merged yet did made same mistake in this PR

**Comment by 0xSage** [comment]
> it is not merged yet did i made some mistake in this PR

Ah no mistakes. Just waiting for @urmauur to do a peer review on Monday :)
He leads our UI efforts among others!

I could LGTM, but I suck at CSS/HTML and have been fired from the team from doing so...

**Review by urmauur — APPROVED** [review]

**Comment by urmauur** [comment]
LGTM, @mishrababhishek thanks for your contribute 🚀

**Pull request merged**
