### PR TITLE
add 'change download button based on OS' feature

### PR DESCRIPTION
**Pull request by Vikram-2004**
**This pull request makes the following changes:**
- fixes issue   #543 

- the button changes as per the os of the client
- defaut is the mac one

### CODE REVIEW

**Review by urmauur — APPROVED** [review]
LGTM

**Comment by Vikram-2004** [comment]
This workflow requires approval from a maintainer . can the maintainer merge these changes please. @dan-jan @urmauur

**Comment by dan-jan** [comment]
@louis-jan @urmauur Either one of you should do the honors!
@Vikram-2004 Thank you for your contribution, welcome onboard!

**Comment by urmauur** [comment]
@Vikram-2004 Merged, we can't wait next your contribution, thank you so much 🚀🚀

**Comment by Vikram-20** [comment]
Thanks for merging.

**Comment by Vikram-2004** [comment]
Thanks for merging .

**Pull request merged**
