### PR TITLE
Update interface landing page

### PR DESCRIPTION
**Pull request by urmauur**
Keep it simple and support both theme

- [x] Dark and light mode Desktop

Screenshot 2023-10-18 at 00 48 17
Screenshot 2023-10-18 at 00 48 27
Screenshot 2023-10-18 at 00 48 36

Screenshot 2023-10-18 at 00 47 23
Screenshot 2023-10-18 at 00 47 31
Screenshot 2023-10-18 at 00 47 47

&nbsp;

- [x] Dark and light mode Mobile

Screenshot 2023-10-18 at 00 51 57
Screenshot 2023-10-18 at 00 52 04

Screenshot 2023-10-18 at 00 51 43
Screenshot 2023-10-18 at 00 51 49

- [x] Added announcement banner

- [x] Added event badge
Screenshot 2023-10-18 at 01 00 20

### CODE REVIEW

**Comment by dan-jan** [comment]
@urmauur Minor changes: 

## Single Column Layout

- I think the "single column" layout will be more maintainable
- Problem: I encounter this problem with the 2-column Hero

image

- Solution: I think your single-column layout looked really beautiful, especially with the large header

image

## Href Links should be more visible

- Problem: Currently, URLs are not highlighted, difficult to tell that it's a link
- Solution: Links / URLs should be more visible? (or easier to tell that it's a href)

image

**Comment by dan-jan** [comment]
@urmauur Also missing a Release Version tag here:

image

**Comment by dan-jan** [comment]
@urmauur - Please also merge in some simply copywriting changes I've made: 

https://github.com/janhq/jan/pull/382

**Comment by urmauur** [comment]
- [ ] Make the Hero into Single Column Layout
- [ ] URLs are not highlighted
- [ ] Defaulting to Dark Mode
- [ ] Missing a Release Version tag

**Comment by 0xSage** [comment]
@urmauur At the moment, it defaults to light mode. 

To default to dark mode, you might have to set `docusuaurus.config.js`: https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode

**Comment by urmauur** [comment]
> @urmauur At the moment, it defaults to light mode.
> 
> To default to dark mode, you might have to set `docusuaurus.config.js`: https://docusaurus.io/docs/api/themes/configuration#color-mode---dark-mode

Already set like docusuaurus docs, can you check your `localstorage`, might be need remove `localstorage` `theme` first ?

so when user first landing on our website user should be not have `theme` on `localstorge`

Screenshot 2023-10-18 at 12 29 09

**Comment by dan-jan** [comment]
@urmauur A couple of last bugs

image

**Review by dan-jan — APPROVED** [review]
Lgtm

**Pull request merged**
