### PR TITLE
feat: support markdown on user message 

### LINKED ISSUE #3358: feat: render code, indents, markdown for user inputs
### #

- [ ] I have searched the existing issues

### Current behavior

Code pasted in with indents renders with 0 indents. However, when going to edit the input, the indents render.

### Minimum reproduction step

Paste code in with indents

### Expected behavior

Code or anything with indents should render correctly for input as well as output. Markdown support would be nice too. 

### Screenshots / Logs

Screenshot 2024-08-12 at 10 56 44 PM
Screenshot 2024-08-12 at 10 56 41 PM

### Jan version

0.5.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Environment details

_No response_

### LINKED ISSUE #3739: idea: Add markdown rendering support to Jan
### Problem Statement
https://github.com/janhq/jan/issues/3358
https://discord.com/channels/1107178041848909847/1288971144837206036
Currently, Jan does not render markdown correctly in user messages to the LLM. This limits the ability of users to format their input in a clear and structured way, which can be particularly important for code snippets, lists, and other structured text. The lack of markdown support affects the readability and usability of the chat interface, especially for technical discussions or when sharing code.

### Feature Idea

Implement markdown rendering support in Jan's chat interface. This would include:

1. Rendering markdown in user input messages:
   - Code blocks with syntax highlighting
   - Inline code formatting
   - Headers
   - Lists (ordered and unordered)
   - Bold and italic text
   - Links
   - Blockquotes

2. Ensure markdown rendering works consistently across different models (e.g., Claude 3.5 Sonnet, as mentioned in the conversation).

3. Include a toggle option to view raw markdown text alongside the rendered version?

### PR DESCRIPTION
**Pull request by urmauur**
## Describe Your Changes

1. **New Rich Editor Component (`RichTextEditor.tsx`)**:
   - A new TypeScript file `RichTextEditor.tsx` is created, which defines a React component for a rich text editor using Slate.js.
   - The component supports basic formatting (bold, italic), inline code blocks, and syntax highlighting for code blocks.

2. **Custom Types for Slate**:
   - The `slate` module declaration is updated to include custom types (`CustomElement`, `CustomText`) that extend the default Slate Editor interface.
   - This allows the editor to handle paragraphs, code blocks, and text with formatting attributes.

3. **Initial Value**:
   - The initial value for the editor is set to a single paragraph element with an empty text field.

4. **Decorate Function**:
   - A custom `decorate` function is implemented to identify code blocks and apply styles (bold, italic) to text ranges.
   - It also handles syntax highlighting for inline and block code using `highlight.js`.

5. **RenderLeaf Function**:
   - The `renderLeaf` function applies the formatting and styling attributes to the text elements in the editor.

6. **Event Handling**:
   - Key handlers like `onKeyDown` are implemented to handle specific key events (e.g., Enter, Tab) for inserting new lines, toggling code blocks, and handling tab indentation.
   - The component also handles state updates and side effects such as focusing the textarea and adjusting its height.

7. **Styling**:
   - The `RichEditor` component includes various CSS classes to style the editor and its content, including syntax highlighting for different programming languages.

8. **Integration with Existing Components**:
   - The `ChatInput.tsx` file is modified to use the new `RichTextEditor` component instead of the old `CodeEditor`.
   - The `RichEditor` component is configured with options such as `className`, `style`, `placeholder`, and `spellCheck`.

9. **Code Refactoring**:
    - The old `TextArea` component is commented out in favor of the new `RichEditor`.
    - Various refactoring and clean-up are done throughout the codebase to integrate the new editor seamlessly with existing components and logic.

These changes significantly enhance the text editing capabilities of the application, allowing for more complex and formatted text input, including support for code blocks with syntax highlighting.

## Fixes Issues

- Support for inline syntax highlighting in the chat input box:
  - Code enclosed within triple backticks (```) will be highlighted for syntax.
  - The chat user’s message will render with the appropriate code syntax highlighting.

Screenshot 2024-10-21 at 12 40 05
Screenshot 2024-10-21 at 12 38 32
Screenshot 2024-10-21 at 12 38 03
Screenshot 2024-10-21 at 12 49 52

- Support for inline text formatting (bold and italic) in the chat input box:
  - Users can apply bold and italic formatting directly within the input box.
  - The chat user’s message will display the correctly formatted text.
  
Screenshot 2024-10-21 at 12 52 07

Screenshot 2024-10-21 at 12 52 39

- Chat user support all markdown 
  - Code blocks with syntax highlighting
  - Lists (ordered and unordered)
  - Bold and italic text
  - Links
  - Blockquotes
  
Screenshot 2024-10-21 at 12 53 23

Screenshot 2024-10-21 at 12 53 43

Screenshot 2024-10-21 at 13 02 48

Screenshot 2024-10-21 at 13 03 15

Note: The reason we only support syntax highlighting and text formatting (bold and italic) in the chat input is to avoid making the input box interface cluttered or unattractive. For example, rendering blockquotes inside the chat input would lead to a messy and visually unappealing interface.

- Closes #3358 
- Closes #3739 

## Self Checklist

- [ ] Added relevant comments, esp in complex areas
- [ ] Updated docs (for bug fixes / features)
- [ ] Created issues for follow-up changes or refactoring needed

### CODE REVIEW

**Comment by imtuyethan** [comment]
Works well on my end.

**Review by louis-jan — APPROVED** [review]
LGTM

**Comment by dan-homebrew** [comment]
Thanks @urmauur, this looks great!

**Comment by LarsArtmann** [comment]
Thanks :)

**Pull request merged**
